import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { marked } from 'marked';

// Committed HTML works on Pages and any static server. Markdown is the source.
const pages = [
  ['artifacts/philosophy', 'Philosophy', '../'],
  ['artifacts/workflow', 'Workflow', '../'],
  ['artifacts/timeline', 'Timeline', '../'],
  ['journal/index', 'Journal Room', '../'],
  ['journal/2026/08-21-repo-excavations', 'Repo Excavations', '../../'],
  ['journal/2026/08-21-what-the-wren-hears', 'What the Wren Hears — Field Note', '../../'],
];
for (const [name, title, root] of pages) {
  let source = readFileSync(`${name}.md`, 'utf8').replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '');
  const style = source.match(/<style>[\s\S]*?<\/style>/)?.[0] || '';
  source = source.replace(style, '').trim();
  // Historical room sources mix block HTML and Markdown; separate the heading.
  source = source.replace(/(<\/span>)\r?\n(?=# )/g, '$1\n\n');
  let content = marked.parse(source);
  content = content.replace(/href="([^"#?:]+)\.md(#[^"]*)?"/g, (_, path, hash = '') =>
    `href="${path.endsWith('/README') ? path.slice(0, -6) + 'index' : path}.html${hash}"`);
  if (!content.includes('class="shell"')) {
    content = `<div class="shell"><nav class="nav" aria-label="Notebook"><a href="${root}">Conversational Artifacts</a><a href="${root}journal/">Journal Room</a><a href="${root}artifacts/philosophy.html">Philosophy</a></nav><article>${content}</article></div>`;
  }
  content = content.replace('<nav class="nav">', '<nav class="nav" aria-label="Notebook">');
  mkdirSync(dirname(name), { recursive: true });
  writeFileSync(`${name}.html`, `<!DOCTYPE html>
<!-- Generated by npm run build from ${name}.md. Edit the Markdown source. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="${title}: notes on conversation, software, and evidence by Tom Harwood.">
<title>${title} · Conversational Artifacts</title>${style}
<link rel="stylesheet" href="${root}assets/notebook.css"></head><body>
<a class="skip-link" href="#main">Skip to content</a><main id="main">${content}</main>
<footer class="notebook-footer"><a href="${root}">Collection</a><span>Still observing.</span><a href="https://github.com/ncypher/ncypher">Tom Harwood / ncypher</a></footer></body></html>\n`);
  console.log(`Built ${name}.html`);
}
